### ISSUE TITLE
woof echoing out

### ISSUE THREAD

**Issue by ronalfy** [nathanmarks/wordpress-gravity-forms-event-tracking#12]
In /includes/class-gravity-forms-event-tracking-feed.php there is an echo that is causing PHP fatal errors because headers are already sent.

Detailed here:  https://wordpress.org/support/topic/woof-on-submit

**Comment by nathanmarks** [comment]
Arggggghh, fixed by https://github.com/nathanmarks/wordpress-gravity-forms-event-tracking/commit/38ff10f34ef51669464543f35916eae1e24f9cbc
