### ISSUE TITLE
Settings Page Disabled when Members Plugin is enabled.

### ISSUE THREAD

**Issue by laurenmancke** [nathanmarks/wordpress-gravity-forms-event-tracking#16]
https://wordpress.org/plugins/members/

**Comment by nathanmarks** [comment]
Thanks!

note for self: incompatibility to investigate!

**Comment by asithade** [comment]
I don't have the members plugin, and the settings page is still not there for me. 

Something to note is that I had already setup the plugin previously, and it seems that the event tracking for items I setup are still being triggered. It's just that I can't go in and edit them.

**Comment by nathanmarks** [comment]
Hmm. What version of gravity?

**Comment by asithade** [comment]
1.8.22

**Comment by asithade** [comment]
Weird. It just suddenly reappeared.

**Comment by nathanmarks** [comment]
Wow.... I'm not sure how that's even possible unless you changed something.

**Comment by asithade** [comment]
Nope. May have possibly been caching but I did not make any changes so definitely weird.

**Comment by nathanmarks** [comment]
Fixed with https://github.com/nathanmarks/wordpress-gravity-forms-event-tracking/commit/c026fcf02af4a1b7065a583b285f2298c2dde4a7
