### ISSUE TITLE
Not registering in analytics

### ISSUE THREAD

**Issue by campbellking** [nathanmarks/wordpress-gravity-forms-event-tracking#17]
Hi Nathan

Great plugin! Was working fine until I recently updated my installation. I have checked all the settings are correct and tested it however no luck :(

I am just tracking basic frm submissions so have left the fields in the set up blank i order to use the defaults.

I am using:
Gravity Forms 1.9.0.1 
Gravity Forms Google Analytics Event Tracking 1.6.2 

Your help would be appreciated in identifying the issue.

Kind regards

Campbell

**Comment by campbellking** [comment]
I note that my UA tracking code is also correctly set up.

**Comment by nathanmarks** [comment]
Hey Campbell can you make sure that the feed is enabled? (Green toggle next to feed on the event tracking form settings tab for each form).

**Comment by campbellking** [comment]
Hi Nathan

Yes I can confirm that the feed switch is on (green). 

The site that the form is on is MiFi.com.au. The form appears in the footer and also as a popup on exit if that helps. 

Thanks for your quick response!

Campbell

On 10 Feb 2015, at 11:24 am, nathanmarks <notifications@github.com> wrote:

Hey Campbell can you make sure that the feed is enabled? (Green toggle next to feed on the event tracking form settings tab for each form).

**Comment by nathanmarks** [comment]
@campbellking Can you try recreate the feed and see if it fixes things?

If not, I can help you **much** more easily if you can create me a temporary admin login.

If that's not possible, can you add this snippet to your functions.php temporarily?

```
function temp_ua_id( $ua_id ) {
    return 'UA-52010108-2';
}
add_filter( 'gform_ua_id', 'temp_ua_id' );
```

**Comment by campbellking** [comment]
Hi Nathan

No luck. I am happy to give you access. What email address should I use?

Really appreciate your help!

Cheers

Campbell

On 10 Feb 2015, at 12:51 pm, nathanmarks <notifications@github.com> wrote:

@campbellking Can you try recreate the feed and see if it fixes things?

If not, I can help you much more easily if you can create me a temporary admin login.

If that's not possible, can you add this snippet to your functions.php temporarily?

function temp_ua_id( $ua_id ) {
    return 'UA-52010108-2';
}
add_filter( 'gform_ua_id', 'temp_ua_id' );

**Comment by nathanmarks** [comment]
Hey @campbellking ,

Use the email address here (there's a captcha so the email can't be picked up by robots): http://scr.im/31yj

**Comment by campbellking** [comment]
Hi Nathan

It looks like it is working now. I will let you know if anything changes.

Cheers

Campbell

On 11 Feb 2015, at 12:11 am, nathanmarks <notifications@github.com> wrote:

Hey @campbellking ,

Use the email address here (there's a captcha so the email can't be picked up by robots): http://scr.im/31yj
