### ISSUE TITLE
Feature request: Conditional events

### ISSUE THREAD

**Issue by intelliweb** [nathanmarks/wordpress-gravity-forms-event-tracking#9]
An interesting next step for this would be to incorporate Gravity Forms conditional logic for the events so that different events can be sent to Google Analytics based on form field data.

And along the same lines, ability to have multiple events.

Specific use case:
Say we have a lead generation form for new clients.  In that form there is a field that asks if they are a new or returning client.  There could be an event for all form submissions in total.  And then also conditional events to track submissions from new clients vs. returning.

**Comment by thompsonpaul** [comment]
@nathanmarks Love what you're doing here! I don't have a client project for this at the moment, but I'd like to offer to add a few bucks to the "bounty" for this feature as well, to help make it more worthwhile to prioritise. 

Paul
paul@paulthompson.ca

**Comment by intelliweb** [comment]
@thompsonpaul and @nathanmarks Still working on getting client approval for this (lot of moving parts on their end) but I'm pretty confident it will get approved.
